# Generated by Django 4.2.1 on 2023-05-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_rename_name_category_catname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Catergories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catName',
            new_name='name',
        ),
    ]
